export const Signup=[
    {
      label: 'First Name',
      type: 'text',
      isDropdown: false,
      required: true,
      options: [],
      depenceOn: [],
    },
    {
      label: 'Last Name',
      type: 'text',
      isDropdown: false,
      required: false,
      options: [],
      depenceOn: ['First Name'],
    },
    {
      label: 'Email',
      type: 'email',
      isDropdown: false,
      required: true,
      options: [],
    },
    {
      label: 'Password',
      type: 'password',
      isDropdown: false,
      required: true,
      options: [],
      depenceOn: [],
    },
    {
      label: 'Confirm Password',
      type: 'password',
      isDropdown: false,
      required: true,
      options: [],
      depenceOn: ['Confrim Password'],
    },
    // {
    //   label: 'Gender',
    //   type: 'select',
    //   isDropdown: true,
    //   required: true,
    //   options: [
    //     {
    //       name: 'Male',
    //     },
    //     {
    //       name: 'Female',
    //     },
    //   ],
    //   depenceOn: [],
    // },
    {
      label: 'Department',
      type: 'select',
      isDropdown: true,
      required: true,
      options: [
        { name: 'EIE' },
        { name: 'CSE' },
        { name: 'IT' },
        { name: 'ECE' },
      ],
      depenceOn: [],
    },
    {
      label: 'Mentor',
      type: 'select',
      isDropdown: true,
      required: true,
      options: [
        { name: 'EIE' },
        { name: 'CSE' },
        { name: 'IT' },
        { name: 'ECE' },
      ],
      depenceOn: ['Department'],
    },
    {
      label: 'Year',
      type: 'select',
      isDropdown: true,
      required: true,
      options: [
        { name: '2020' },
        { name: '2021' },
        { name: '2022' },
        { name: '2023' },
        { name: '2024' },
        { name: '2025' },
        { name: '2026' },
      ],
      depenceOn: [],
    },

]
